import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("prices_round_5_day_2.csv", sep=";")

summary = df.groupby("product")["mid_price"].agg(["mean", "std", "min", "max"])
summary["range"] = summary["max"] - summary["min"]
summary['cv'] = summary['std'] / summary['mean']
print(summary.sort_values('cv'))

SNACKPACK = ["SNACKPACK_CHOCOLATE", "SNACKPACK_PISTACHIO", "SNACKPACK_VANILLA", "SNACKPACK_RASPBERRY", "SNACKPACK_STRAWBERRY"]

TRANSLATOR = ["TRANSLATOR_ASTRO_BLACK", "TRANSLATOR_GRAPHITE_MIST", "TRANSLATOR_SPACE_GRAY", "TRANSLATOR_VOID_BLUE", "TRANSLATOR_ECLIPSE_CHARCOAL"]

PANEL = ["PANEL_2X2", "PANEL_4X4", "PANEL_2X4", "PANEL_1X4", "PANEL_1X2"]

OXYGEN_SHAKE = ["OXYGEN_SHAKE_MINT", "OXYGEN_SHAKE_CHOCOLATE", "OXYGEN_SHAKE_MORNING_BREATH", "OXYGEN_SHAKE_GARLIC", "OXYGEN_SHAKE_EVENING_BREATH"]

UV_VISOR = ["UV_VISOR_ORANGE", "UV_VISOR_RED", "UV_VISOR_MAGENTA", "UV_VISOR_AMBER", "UV_VISOR_YELLOW"]

ROBOT = ["ROBOT_VACUUMING", "ROBOT_LAUNDRY", "ROBOT_MOPPING", "ROBOT_DISHES", "ROBOT_IRONING"]

MICROCHIP = ["MICROCHIP_TRIANGLE", "MICROCHIP_CIRCLE", "MICROCHIP_OVAL", "MICROCHIP_RECTANGLE", "MICROCHIP_SQUARE"]

GALAXY_SOUNDS = ["GALAXY_SOUNDS_DARK_MATTER", "GALAXY_SOUNDS_SOLAR_WINDS", "GALAXY_SOUNDS_SOLAR_FLAMES", "GALAXY_SOUNDS_PLANETARY_RINGS", "GALAXY_SOUNDS_BLACK_HOLES"]

SLEEP_POD = ["SLEEP_POD_NYLON", "SLEEP_POD_COTTON", "SLEEP_POD_LAMB_WOOL", "SLEEP_POD_SUEDE", "SLEEP_POD_POLYESTER"]

PEBBLES = ["PEBBLES_M", "PEBBLES_S", "PEBBLES_L", "PEBBLES_XS", "PEBBLES_XL"]

GROUPS = {"SNACKPACK": SNACKPACK, "TRANSLATOR": TRANSLATOR, "PANEL": PANEL, "OXYGEN_SHAKE": OXYGEN_SHAKE, "UV_VISOR": UV_VISOR, "ROBOT": ROBOT, "MICROCHIP": MICROCHIP, "GALAXY_SOUNDS": GALAXY_SOUNDS, "SLEEP_POD": SLEEP_POD, "PEBBLES": PEBBLES}

